accounts/urls.py
from django.urls import path, re_path, include
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    # path('',login, name='login'),
    path('login/',CustomLoginView.as_view(), name = 'login'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    # path('register/',register, name='register'),
    path('register/',CustomRegisterView.as_view(), name='register'),
    path('change-password/',change_password, name='change-password'),
    path('forget-password/',forget_password, name='forget-password'),
    # path('reset-password/',reset_password, name='reset-password'),
    path('reset-password/', ReserPasswordView.as_view(), name='reset_password'),
    # path('password-reset-confirm/uidb64 token', ReserPasswordView.as_view(), name='password-reset-confirm')
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('api/', include('accounts.api.urls'))
]

stories/urls.py
from django.urls import path, include
from .views import *
# from api.urls import urlpatterns as api_urls


app_name = 'stories'

urlpatterns = [
    path('',index, name='index'), #home
    # path('about/',about, name='about'),
    path('about/',AboutView.as_view(), name='about'),
    # path('contact/',ContactView.as_view(), name='contact'),
    path('contact/',ContactView.as_view(), name='contact'),
    # path('contact/',contact, name='contact'),
    path('create_story/',create_story, name='create_story'),
    path('email_subscribers/',email_subscribers, name='email_subscribers'),
    # path('recipes/',recipes, name='recipes'),
    path('recipes/',RecipeView.as_view(), name='recipes'),
    # path('single/<int:pk>/',single, name='single'), #int is the integer / pk is the primary key
    path('single/<int:pk>/',SingleRecipeView.as_view(), name='single'), 
    path('stories/',stories, name='stories'),
#   path('user_profile/<int:pk>',user_profile, name='user_profile')
    path('user-profile/<int:pk>/',UserProfileView.as_view(), name='user-profile'),
    path('user-edit/<int:pk>/',UserEditView.as_view(), name='user-edit'),
    path('subscribe/', SubscriberView.as_view(), name='subscribe'),
    path("api/", include('stories.api.urls')),
]

# urlpatterns += api_urls

stories_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('',include('stories.urls', namespace='stories')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
{% load static base_filters %}

<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                    {% get_categories as categories %}
                    {% for category in categories|slice:":4" %}
                        <li><a href="#" class="py-2 d-block">{{category.title}}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

templates/partials/header.html
{% load base_filters %}
{% get_nav_links as nav_links %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
    </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">

                {% for link in nav_links %}
                    {% if link.url == '/accounts/login' %}
                        {% if not user.is_authenticated %}
                            <li class="nav-item active"><a href="{{ link.url }}" class="nav-link">{{ link.title }}</a></li>
                            {% else %}
                             <li class="nav-item active"><a href="{% url 'accounts:logout' %}" class="nav-link">Log out</a></li>
                             <li class="nav-item active"><a href="{% url 'stories:user-profile' request.user.id %}" class="nav-link">Profile</a></li>
                        {% endif %}
                    {% elif link.url == '/accounts/register' %}
                        {% if not user.is_authenticated %}
                            <li class="nav-item active"><a href="{{ link.url }}" class="nav-link">{{ link.title }}</a></li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item active"><a href="{{ link.url }}" class="nav-link">{{ link.title }}</a></li>
                    {% endif %}
                {% endfor %}
                    {% comment %} <li class="nav-item"><a href='{{link.url}}' class="nav-link">{{link.title}}</a></li>
                    <li class="nav-item"><a href='{{link.url}}' class="nav-link">{{link.title}}</a></li>
                    <li class="nav-item"><a href='{{link.url}}' class="nav-link">{{link.title}}</a></li>
                    <li class="nav-item"><a href='{{link.url}}' class="nav-link">{{link.title}}</a></li> {% endcomment %}

                    {% comment %} <li class="nav-item"><a href='{% url "stories:about" %}' class="nav-link">About</a></li>
                    <li class="nav-item"><a href='{% url "stories:stories" %}' class="nav-link">Stories</a></li>
                    <li class="nav-item"><a href='{% url "stories:recipes" %}' class="nav-link">Recipes</a></li>
                    <li class="nav-item"><a href='{% url "stories:contact" %}' class="nav-link">Contact</a></li>  {% endcomment %}
                                                                                                                                                                                                                                                                                                               
                {% comment %} <li><a href="{% url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
                <li><a href="{% url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3">Sign up</a></li>  {% endcomment %}
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

templates/partials/subscribers.html
{% load base_filters %}

<section class="ftco-subscribe ftco-section bg-light">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                        <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                        <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                        <div class="row d-flex justify-content-center mt-4 mb-4">
                            <div class="col-md-8">
                                <form action="{% url 'stories:subscribe' %}" method="POST" class="subscribe-form">
                                    {% get_subscriber_form as form %}
                                    <div class="form-group d-flex">
                                        {% csrf_token %}
                                        {{ form.non_field_errors }}
                                        {{ form }}
                                        {{ form.errors }}
                                        {% comment %} <input type="text" class="form-control" placeholder="Enter email address"> {% endcomment %}
                                        <input type="submit" value="Subscribe" class="submit px-3">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>