accounts/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('login/', obtain_auth_token, name='api=login')
]

accounts/urls.py
from django.urls import path, re_path, include
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    # path('',login, name='login'),
    path('login/',CustomLoginView.as_view(), name = 'login'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    # path('register/',register, name='register'),
    path('register/',CustomRegisterView.as_view(), name='register'),
    path('change-password/',change_password, name='change-password'),
    path('forget-password/',forget_password, name='forget-password'),
    # path('reset-password/',reset_password, name='reset-password'),
    path('reset-password/', ReserPasswordView.as_view(), name='reset_password'),
    # path('password-reset-confirm/uidb64 token', ReserPasswordView.as_view(), name='password-reset-confirm')
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('api/', include('accounts.api.urls'))
]

stories/urls.py
from django.urls import path, include
from .views import *
# from api.urls import urlpatterns as api_urls


app_name = 'stories'

urlpatterns = [
    path('',index, name='index'), #home
    # path('about/',about, name='about'),
    path('about/',AboutView.as_view(), name='about'),
    # path('contact/',ContactView.as_view(), name='contact'),
    path('contact/',ContactView.as_view(), name='contact'),
    # path('contact/',contact, name='contact'),
    path('create_story/',create_story, name='create_story'),
    path('email_subscribers/',email_subscribers, name='email_subscribers'),
    # path('recipes/',recipes, name='recipes'),
    path('recipes/',RecipeView.as_view(), name='recipes'),
    # path('single/<int:pk>/',single, name='single'), #int is the integer / pk is the primary key
    path('single/<int:pk>/',SingleRecipeView.as_view(), name='single'), 
    path('stories/',stories, name='stories'),
#   path('user_profile/<int:pk>',user_profile, name='user_profile')
    path('user-profile/<int:pk>/',UserProfileView.as_view(), name='user-profile'),
    path('user-edit/<int:pk>/',UserEditView.as_view(), name='user-edit'),
    path('subscribe/', SubscriberView.as_view(), name='subscribe'),
    path("api/", include('stories.api.urls')),
]

# urlpatterns += api_urls

stories_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('',include('stories.urls', namespace='stories')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms 
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm

User = get_user_model()


class CustomLoginForm(AuthenticationForm):
    username = UsernameField(label='', widget=forms.TextInput(attrs={
        'autofocus': True, 
        'class': 'form-control',
        'placeholder': "Username",
    }))
    password = forms.CharField(
        label='',
        strip=False, 
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': "Password",
        }),
    )

class CustomRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Username'
    }))

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'First Name'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Last Name'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class':'form-control',
        'placeholder': 'Email'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class':'form-control',
        'placeholder': 'Password'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class':'form-control',
        'placeholder': 'Confirm Password'
    }))
    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email', 'password1', 'password2',]


class CustomResetPasswordForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
    }), max_length=254)

class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'New password'
    }))
    
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm new password'
    }))

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from .forms import CustomLoginForm, CustomRegisterForm, CustomResetPasswordForm, CustomSetPasswordForm
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView, PasswordResetForm, PasswordResetConfirmView

User = get_user_model() #when required to write custom user tools

# Create your views here.


def change_password(request):
    return render(request, 'change_password.html')

def forget_password(request):
    return render(request, 'forget_password.html')

# def login(request):
#     return render(request, 'login.html')
class CustomLoginView(LoginView):
    template_name = 'login.html'
    form_class = CustomLoginForm
    

# def register(request):
#     return render(request, 'register.html')
class CustomRegisterView(CreateView):
    model = User
    template_name = 'register.html'
    # fields = '__all__'
    form_class = CustomRegisterForm
    success_url = reverse_lazy('accounts:login')


def reset_password(request):
    return render(request, 'reset_password.html')


class ReserPasswordView(PasswordResetView):
    form_class = CustomResetPasswordForm
    template_name = 'forget_password.html'
    email_template_name = 'password_reset_email.html'
    success_url = reverse_lazy('stories:index')

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'reset_password.html'
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy('accounts:login')

accounts/templates/change_password.html
{% extends "base/index.html" %}
{% load static %}
{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="#" class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <h4 class="reset center">Change your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="New password">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Re-enter new password">
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Change password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock  %}

accounts/templates/forget_password.html
{% extends "base/index.html" %}
{% load static %}
{% block  content%}
 <section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method='POST' class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <h4 class="reset center">Reset password</h4>
                            <h6 class="center">Please enter your email address to request a password reset.</h6>
                        </div>
                        {{form.non_field_errors}}
                        {% csrf_token %}
                        <div class="form-group">
                        {{form.email}}
                        {{form.email.errors}}
                        </div> 
                        {% comment %} <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email">
                        </div> {% endcomment %}
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock  %}

accounts/templates/login.html
{% extends "base/index.html" %}
{% load static %}
{% load socialaccount %}
{% block css %}
    <link rel="stylesheet" href="http:////netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
{% endblock %}

{% block  content%}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% comment %} <div class="form-group">
                            <input type="text" class="form-control" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Password">
                        </div> {% endcomment %}
                        {% comment %} {{form}} {% endcomment %}
                        {% csrf_token %}
                        {{ form.non_field_errors}}
                        {% for field in form %}
                            <div class="form-group">
                                {{field}}
                            </div> 
                        {% endfor %}
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                            <a href="#" class="forgot-password">Forgot password?</a>
                        </div>
                        <div class="form-group">
                            <a href="#" class="">Don't have an account? Sign up</a>
                        </div>
			<div class="form-group center">
                            <a href="{% provider_login_url 'facebook' %}" class="social"><i class="fa fa-facebook social-login fb-color"></i></a>
                            <a href="{% provider_login_url 'google' %}" class="social"><i class="fa fa-google-plus social-login google-color"></i></a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock  %}

accounts/templates/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}
    
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
    
{% endautoescape %}

accounts/templates/register.html
{% extends "base/index.html" %}
{% load static %}
{% block  content%}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {% comment %} {{form.errors}} {% endcomment %}
                        {% comment %} {{form.non_field_errors}} {% endcomment %}
                        {% for field in form %}
                        <div class="form-group">
                            <span class="alert-danger">{{field.errors}}</span>
                            {{field}}
                        </div>
                        {% endfor %}
                        {% comment %} <div class="form-group">
                            <input type="text" class="form-control" placeholder="First name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Last name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Confirm password">
                        </div>
                        {% endcomment %}
                        <div class="form-group">
                            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                        </div> 
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock  %}

accounts/templates/reset_password.html
{% extends "base/index.html" %}
{% load static %}
{% block  content%}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method='POST' class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <h4 class="reset center">Reset your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        {{form.non_field.errors}}
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                            {{field}}
                            {{field.errors}}
                        </div>
                        {% endfor %}
                        {% comment %} <div class="form-group">
                            <input type="email" class="form-control" placeholder="New password">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Re-enter new password">
                        </div> {% endcomment %}
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock  %}