stories/api/urls.py
from django.urls import path
from .views import *
from .routers import router

urlpatterns = [
    path('recipes/', RecipeAPIView.as_view(), name='api-recipes' ),
    path('recipes/<int:id>/', RecipeChangeAPI.as_view(), name='api-recipes-change' ),
]

urlpatterns += router.urls 

stories/urls.py
from django.urls import path, include
from .views import *
# from api.urls import urlpatterns as api_urls


app_name = 'stories'

urlpatterns = [
    path('',index, name='index'), #home
    # path('about/',about, name='about'),
    path('about/',AboutView.as_view(), name='about'),
    # path('contact/',ContactView.as_view(), name='contact'),
    path('contact/',ContactView.as_view(), name='contact'),
    # path('contact/',contact, name='contact'),
    path('create_story/',create_story, name='create_story'),
    path('email_subscribers/',email_subscribers, name='email_subscribers'),
    # path('recipes/',recipes, name='recipes'),
    path('recipes/',RecipeView.as_view(), name='recipes'),
    # path('single/<int:pk>/',single, name='single'), #int is the integer / pk is the primary key
    path('single/<int:pk>/',SingleRecipeView.as_view(), name='single'), 
    path('stories/',stories, name='stories'),
#   path('user_profile/<int:pk>',user_profile, name='user_profile')
    path('user-profile/<int:pk>/',UserProfileView.as_view(), name='user-profile'),
    path('user-edit/<int:pk>/',UserEditView.as_view(), name='user-edit'),
    path('subscribe/', SubscriberView.as_view(), name='subscribe'),
    path("api/", include('stories.api.urls')),
]

# urlpatterns += api_urls

stories_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('',include('stories.urls', namespace='stories')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/models.py
from django.contrib.auth.models import User
from django.db import models
from djrichtextfield.models import RichTextField

# Create your models here.

class AboutPage(models.Model):
    title = models.CharField(max_length=255, blank=False, null=True)
    description = models.TextField(blank=False, null=True)
    #logs

    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class NavLinks(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    url = models.CharField(max_length=20, blank=True)
    active = models.BooleanField(default=True)

    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Contact(models.Model):
    name = models.CharField(max_length = 30, blank=False, null = False)
    # email = models.EmailField('e-Poct',blank = False, null = False)
    email = models.EmailField(blank = False, null = False)
    subject = models.CharField(max_length = 60, blank=False, null = False)
    message = models.TextField(blank = False,null = False)
    #logs

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Story(models.Model):
    title = models.CharField(max_length=50, blank=False, null=True)
    created_at = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to='stories', blank=False, null= True)
    description = models.TextField(blank=False)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='stories',null=True)# class Category-ni bura elave edirik etc. Category 'Lunch-in icine class Categoryde muxtelif lunch-lar elave edirik sonra Story-se elave edirik'
    updated_at = models.DateTimeField(auto_now = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='stories', default=1) #default=1 default user owner of recipes
    view_count = models.PositiveIntegerField('View count', default=0) # checks how many ppl watched the story

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Hekaye'
        verbose_name_plural = 'Hekayeler'

class Category(models.Model):
    title = models.CharField(max_length=50, blank=False, null=True)
    image = models.ImageField(upload_to='categories')
    #logs
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

class Recipe(models.Model):
    title = models.CharField(max_length=50, blank=False, null=True)
    created_at = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to='recipes', blank=False, null= True)
    description = models.TextField(blank=False)
    long_description = RichTextField('long description')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='recipes',null=True)
    updated_at = models.DateTimeField(auto_now = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipes', default=1)
    view_count = models.PositiveIntegerField('View count', default=0) # checks how many ppl watched the recipe

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Resept'
        verbose_name_plural = 'Reseptler'


class Comment(models.Model):
    user = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    comment = models.TextField('Comment',)
    recipe = models.ForeignKey(Recipe, related_name='comments', on_delete=models.CASCADE, null = True, blank = True)
    story = models.ForeignKey(Story, related_name='comments', on_delete=models.CASCADE, null = True, blank = True)
    reply_comment = models.ForeignKey('self', related_name = 'reply_comments', on_delete = models.CASCADE,null = True, blank = True)

#logs
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}" #return "{} {}".format(self.user.first_name, self.user.last_name) is equial to  f"{self.user.first_name} {self.user.last_name}"

    def get_user_full_name(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

    class Meta:
        ordering = ('create_at',)
        verbose_name = 'Rey'
        verbose_name_plural = 'Reyler'


class Subscriber(models.Model):
    email = models.EmailField(max_length=60)
    #logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

stories/forms.py
from django import forms 
from .models import *

class ContactForm(forms.ModelForm):
    name = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your Name'
    }) ,max_length = 20)
    email = forms.CharField(label='',widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your Email'
    }) ,max_length = 20)
    subject = forms.CharField(label='',widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Subject'
    }) ,max_length = 1000)
    message = forms.CharField(label='',widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Your Message',
        'cols': '30',
        'rows': '7',
    }) ,max_length = 1000)

    # c = forms.CharField(label = 'bura c fieldidir', max_length = 20)

    class Meta:
        model = Contact
        fields = '__all__'
        # fields = ['message','c']

class CommentForm(forms.ModelForm):
    comment = forms.CharField(label='Your comment',widget=forms.Textarea(attrs={
        'class':'form-control',
    }))
    class Meta:
        model = Comment
        fields = ['comment',]


class EditUserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Username'
    }))

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'First Name'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Last Name'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class':'form-control',
        'placeholder': 'Email'
    }))

    # password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    #     'class':'form-control',
    #     'placeholder': 'Password'
    # }))

    # password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    #     'class':'form-control',
    #     'placeholder': 'Confirm Password'
    # }))
    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email',]


    

class SubscriberForm(forms.ModelForm):
    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter email address',
    }))
    class Meta:
        model = Subscriber
        fields = ['email']

stories/api/views.py
from rest_framework.views import APIView
from stories.models import Recipe
from django.http import JsonResponse
from .serializers import RecipeSerializer, RecipeCreateSerializer
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticated

class RecipeAPIView(APIView):
    def get(self, request, *args, **kwargs):
        recipes = Recipe.objects.all()
        serializer = RecipeSerializer(recipes, many=True, context={
            'request': request
        })
        return JsonResponse({
            'recipes': serializer.data
        })

    def post(self, request, *args, **kwargs):
        recipe_data = request.data
        serializer = RecipeCreateSerializer(data=recipe_data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors)


class RecipeChangeAPI(APIView):
    def get(self, request, *args, **kwargs):
        recipes = Recipe.objects.get(id=kwargs.get('id'))
        serializer = RecipeSerializer(recipes, context={
            'request': request
        })
        return JsonResponse({
            'recipes': serializer.data
        })

    def put(self, request, *args, **kwargs):
        recipe = Recipe.objects.get(id=kwargs.get('id'))
        updated_recipe_data = request.data
        serializer = RecipeCreateSerializer(data=updated_recipe_data, instance=recipe)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors)

    def patch(self, request, *args, **kwargs):
        recipe = Recipe.objects.get(id=kwargs.get('id'))
        updated_recipe_data = request.data
        serializer = RecipeCreateSerializer(data=updated_recipe_data, instance=recipe, partial=True)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors)

    def delete(self, request, *args, **kwargs):
        recipe = Recipe.objects.get(id=kwargs.get('id')).first()
        if recipe:
            recipe.delete()
            return JsonResponse({}, status=204)
        return JsonResponse({
                'detail': 'Not found',
            }, status=404)


class RecipeAPIViewSet(ModelViewSet):
    permission_classes = [IsAuthenticated]
    queryset = Recipe.objects.all()
    serializer_class = RecipeCreateSerializer

stories/views.py
from django.shortcuts import render
from stories.models import *
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from .forms import *
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views.generic.edit import FormMixin, UpdateView
from django.contrib.auth.models import User
from stories.forms import *

# Create your views here.

# def about(request):
#     context = {}
#     if request.method == 'GET':
#         context['content'] = AboutPage.objects.last()
#     return render(request, 'stories/about.html', context)

class AboutView(TemplateView):
    template_name = 'stories/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['content'] = AboutPage.objects.last()
        return context

# def contact(request):
#     form = ContactForm()
#     context = {
#         'form': form
#     }
#     if request.method == "POST":
#         print(request.POST)
#         # print('Post sorgusu geldi!')
#         form = ContactForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             context['message'] = 'Your message sent successfully'
#         else:
#             context['form'] = form.errors
#     return render(request, 'stories/contact.html', context)

class ContactView(CreateView):
    model = Contact
    template_name = 'stories/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('stories:contact')


class SubscriberView(CreateView):
    model = Subscriber 
    form_class = SubscriberForm
    success_url = reverse_lazy('stories:index')
    http_method_names = ('post',)    

def create_story(request):
    return render(request, 'stories/create_story.html')

def email_subscribers(request):
    return render(request, 'stories/email-subscribers.html')

def index(request):
    return render(request, 'stories/index.html')

# def recipes(request):
#     page_number = request.GET.get('page', 1)
#     recipes = Recipe.objects.all()
#     p = Paginator(recipes, 1) # 1 means how many objects on the page
#     # if isinstance(page_number, int) and int(page_number) > p.num_pages:
#     #     page_number = p.num_pages

#     if not page_number.isdigit():
#         page_number = 1
#     elif int(page_number) > p.num_pages:
#         page.number = p.num_pages
#     recipe_list = p.page(page_number)  #p.page(1) # 1 shows 1-st page, if we put Number 2... shows others
#     # print('recipes', recipes)
#     context = {
#         'recipes': recipe_list  #recipes
#     }
#     return render(request, 'stories/recipes.html', context)

class RecipeView(ListView):
    model = Recipe
    template_name = 'stories/recipes.html'
    context_object_name = 'recipes'
    paginate_by = 1 #number of pages

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     print(context)
    #     context['categories'] = Category.objects.all()
    #     return context // base_filters-de  @register.simple_tag
                                            # def get_categories():
                                            #     return Category.objects.all()
                                            #     oz uzerine goturur



# def single(request, pk):
#     recipe = Recipe.objects.get(id=pk)
#     context = {
#         'recipe_data':recipe,
#     }
#     return render(request, 'stories/single.html', context)

class SingleRecipeView(FormMixin, DetailView): # Single-nin class base-i
    model = Recipe
    template_name = "stories/single.html"
    context_object_name = "recipe_data"
    form_class = CommentForm

    # def get_queryset(self, request, *args, **kwargs):

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.view_count = obj.view_count + 1
        obj.save()
        return obj
    

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.replied_comment = request.POST.get('reply_comment')
        form = self.get_form()
        # form.save(commit=False)
        if form.is_valid():
            print('here')
            return self.form_valid(form)
        else:
            print('here 2')
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.recipe = self.object
        if not self.replied_comment is None and self.replied_comment.isdigit():
            r_comment = Comment.objects.get(id=int(self.replied_comment))
            comment.reply_comment = r_comment 
        comment.save()
        self.success_url = reverse_lazy('stories:single', kwargs=
        {'pk': self.object.id})
        return super().form_valid(form)




def stories(request):
    return render(request, 'stories/stories.html')

# def user_profile(request):
#     return render(request, 'stories/user_profile.html')

class UserProfileView(DetailView):
    model = User
    template_name = 'stories/user-profile.html'

class UserEditView(UpdateView):
    model = User
    template_name = 'stories/user-edit.html'
    form_class = EditUserForm

    def get_success_url(self):
        return reverse_lazy('stories:user-profile' , kwargs={'pk': self.request.user.pk})

stories/templates/stories/about.html
{% extends 'base/index.html' %}
{% load static base_filters %}
{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_4.jpg' %}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About Us</h1>  
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About us<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img d-flex align-self-stretch" style="background-image:url('{% static 'images/about.jpg' %}');"></div>
            </div>
            <div class="col-md-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        {% comment %} <h2 class="mb-4"><span>{{content.title}}</span></h2>
                        <p>{{ content.description}}</p> {% endcomment %}
                        <h2 class="mb-4"><span>{{content.title|custom_text_edit:'upper'}}</span></h2> <!----custom_capitalize|capwords-->
                        <p>{{ content.description|custom_text_edit:'lower'}}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="100">0</strong>
                                <span>Daily visitors</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="200">0</strong>
                                <span>Stories</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="300">0</strong>
                                <span>Recipes</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="40">0</strong>
                                <span>Users</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

stories/templates/stories/create_story.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}

    <section class="ftco-section contact-section create-story">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="#" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>

                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Title">
                        </div>
                        <div class="form-group">
                            <textarea rows="10" class="form-control" placeholder="Description"></textarea>
                        </div>
                        <div class="form-group">
                            <select class="form-control" name="" id="">
                                    <option value="0">Select category</option>
                                    <option value="1">-----</option>
                                
                                </select>
                        </div>

                        <div class="form-group">
                            <input type="file">
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
 {% endblock content %}

stories/templates/stories/user-edit.html
{% extends "base/index.html" %}
{% load static %}
{% block  content%}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {% comment %} {{form.errors}} {% endcomment %}
                        {% comment %} {{form.non_field_errors}} {% endcomment %}
                        {% for field in form %}
                        <div class="form-group">
                            <span class="alert-danger">{{field.errors}}</span>
                            {{field}}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <input type="submit" value="Update" class="btn btn-primary py-3 px-5">
                        </div> 
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock  %}

stories/templates/stories/user-profile.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}

    <section class="ftco-section ftco-no-pt ">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="user-profile-side-bar sidebar-wrap">
                        <div class="sidebar-box p-4 about text-center ftco-animate">
                            <h2 class="heading mb-4">About Me</h2>
                            <img src='{% static "images/author.jpg" %}' class="img-fluid" alt="Colorlib Template">
                            <div class="text pt-4">
                                <p>Hi! My name is <strong>{{ request.user.first_name }}</strong>, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics,
                                    a large language ocean.</p>
                            </div>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">

                            <a href="{% url 'stories:user-edit' request.user.pk %}" class="btn btn-hover-color py-2">Edit Profile</a>

                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="single.html" class="btn btn-hover-color py-2">Create story </a>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="single.html" class="btn btn-hover-color py-2">Create recipe </a>
                        </div>
                        <div class="sidebar-box p-4 ftco-animate">
                            <form action="#" class="search-form">
                                <div class="form-group">
                                    <span class="icon icon-search"></span>
                                    <input type="text" class="form-control" placeholder="Search">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-md-12 heading-section ftco-animate">
                            <h2 class="mb-4"><span>My stories and recipes</span></h2>
                        </div>
                    </div>
                    <div class="row">
                        {% for story in request.user.stories.all %}
                            <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">

                                    <div class="user-events__edit">
                                        <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                        <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>

                                    {% comment %} <img src='{% static "images/blog-1.jpg" %}' class="img-fluid" alt="Colorlib Template"> {% endcomment %}
                                    <img src='{{ story.image.url }}' class="img-fluid" alt="Colorlib Template">
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">{{ story.category.title }}</span><span class="ml-auto pl-3">{{ story.created_at|date:'F d,Y' }}</span>
                                    </p>
                                    <h3><a href="#">{{ story.title }} &amp;</a></h3>
                                    <p class="mb-0"><a href="{% url 'stories:single' story.id %}" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        
                       
                    </div>
                </div>


            </div>
        </div>
    </section>
{% endblock content %}